#!/bin/sh /etc/rc.common

START=99
STOP=0

USE_PROCD=1
#PROCD_DEBUG=1

start_service() {

	procd_open_instance

        procd_set_param command /etc/hamq.d/hostapd_mapper_wrapper

	procd_close_instance

}

