#!/bin/sh /etc/rc.common
#
# procd wrapper for hostapd_cli
# run hostapd_cli per wireless interface in /var/run/hostapd/
# and call the hostapd_tracker script (which publishes to mqtt) 
# in /etc/hamq.d/
#

START=99
STOP=0

USE_PROCD=1


start_service() {

  for iface in /var/run/hostapd/* ; do
    if [ -e "$iface" ] ; then
        iface="${iface##*/}"

	procd_open_instance
	procd_set_param command hostapd_cli -i"$iface" -a/etc/hamq.d/hostapd_tracker
	# procd_set_param stdout 1
	# procd_set_param stderr 1
	procd_close_instance

   fi
  done

}

